import * as cornerstoneTools from "@cornerstonejs/tools";
import { toast } from "sonner";
import { persistSubmission } from "./sessionSubmissions.js";

export function participantHasSubmitted(userId, submittedAnnotations, submittedQuestionAnswers) {
  if (!userId) return false;
  return !!(submittedAnnotations?.[userId] || submittedQuestionAnswers?.[userId]);
}

export function collectUnsubmittedBoxes() {
  try {
    const mgr = cornerstoneTools.annotation.state;
    return mgr
      .getAllAnnotations()
      .filter((a) => a.metadata?.toolName === "RectangleROI" && !a.isLocked);
  } catch {
    return [];
  }
}

export function submitParticipantResponse({
  userId,
  userName,
  answers,
  interactionChannel,
  dispatch,
  renderingEngine,
  submittedAnnotations,
  submittedQuestionAnswers,
  supabaseClient,
  sessionId,
  caseKey,
}) {
  if (participantHasSubmitted(userId, submittedAnnotations, submittedQuestionAnswers)) {
    toast.info("You already submitted for this session", { duration: 2000 });
    return false;
  }

  const rects = collectUnsubmittedBoxes();
  const boxes = rects.map((a) => ({
    imageId: a.metadata?.referencedImageId || "",
    points: a.data?.handles?.points || [],
  }));

  const answerCount = Object.keys(answers || {}).length;
  if (answerCount === 0 && boxes.length === 0) {
    toast.info("Answer a question or draw a box before submitting", { duration: 2500 });
    return false;
  }

  if (boxes.length > 0) {
    const boxPayload = { userId, userName, boxes };
    interactionChannel?.send({
      type: "broadcast",
      event: "annotations-submitted",
      payload: boxPayload,
    });
    dispatch({ type: "annotation_received", payload: boxPayload });

    rects.forEach((a) => {
      a.isLocked = true;
      a.autoGenerated = true;
    });
  }

  if (answerCount > 0) {
    const answerPayload = { userId, userName, answers };
    interactionChannel?.send({
      type: "broadcast",
      event: "question-answers-submitted",
      payload: answerPayload,
    });
    dispatch({ type: "question_answer_received", payload: answerPayload });
  }

  renderingEngine?.getViewports().forEach((vp) => vp.render());

  // Durably persist alongside the live broadcast so the leaderboard survives
  // reloads/transfers and is visible to clients that weren't connected yet.
  if (sessionId && caseKey) {
    persistSubmission({
      supabaseClient,
      sessionId,
      caseKey,
      userId,
      userName,
      answers: answerCount > 0 ? answers : null,
      boxes,
    }).catch((e) => console.error("Failed to persist submission:", e));
  }

  const parts = [];
  if (answerCount > 0) parts.push(`${answerCount} answer${answerCount !== 1 ? "s" : ""}`);
  if (boxes.length > 0) parts.push(`${boxes.length} box${boxes.length !== 1 ? "es" : ""}`);
  toast.success(`Submitted ${parts.join(" and ")}`, { duration: 2000 });
  return true;
}
