import { useContext, useState, useEffect, useCallback } from "react";
import { Trash2, Send, Eye, EyeOff } from "lucide-react";
import { DataContext, DataDispatchContext } from "../context/DataContext.jsx";
import { UserContext } from "../context/UserContext.jsx";
import * as cornerstoneTools from "@cornerstonejs/tools";
import { eventTarget } from "@cornerstonejs/core";
import { toast } from "sonner";
import { clearBoxHeatmap } from "../lib/heatmapUtils.js";

function AnnotationPanel() {
  const {
    toolSelected,
    interactionChannel,
    renderingEngine,
    sessionId,
    sessionMeta,
    submittedAnnotations,
    heatmapVisible,
  } = useContext(DataContext).data;
  const { userData } = useContext(UserContext).data;
  const { dispatch } = useContext(DataDispatchContext);
  const [annotationCount, setAnnotationCount] = useState(0);
  const [totalAnnotationCount, setTotalAnnotationCount] = useState(0);

  const isSessionOwner = sessionId && userData && sessionMeta?.owner === userData.id;
  const submissionCount = Object.keys(submittedAnnotations || {}).length;
  const totalBoxes = Object.values(submittedAnnotations || {}).reduce(
    (sum, sub) => sum + (sub?.boxes?.length || 0),
    0
  );

  const countAnnotations = useCallback(() => {
    try {
      const mgr = cornerstoneTools.annotation.state;
      const all = mgr.getAllAnnotations();
      const allRects = all.filter(
        (a) => a.metadata?.toolName === "RectangleROI"
      );
      const unsubmitted = allRects.filter((a) => !a.isLocked);
      setAnnotationCount(unsubmitted.length);
      setTotalAnnotationCount(allRects.length);
    } catch {
      setAnnotationCount(0);
      setTotalAnnotationCount(0);
    }
  }, []);

  useEffect(() => {
    if (toolSelected !== "annotate" || isSessionOwner) return;

    countAnnotations();

    const handler = () => requestAnimationFrame(countAnnotations);

    eventTarget.addEventListener(
      cornerstoneTools.Enums.Events.ANNOTATION_COMPLETED,
      handler
    );
    eventTarget.addEventListener(
      cornerstoneTools.Enums.Events.ANNOTATION_REMOVED,
      handler
    );

    return () => {
      eventTarget.removeEventListener(
        cornerstoneTools.Enums.Events.ANNOTATION_COMPLETED,
        handler
      );
      eventTarget.removeEventListener(
        cornerstoneTools.Enums.Events.ANNOTATION_REMOVED,
        handler
      );
    };
  }, [toolSelected, countAnnotations, isSessionOwner]);

  const handleClearAll = () => {
    try {
      const mgr = cornerstoneTools.annotation.state;
      const all = mgr.getAllAnnotations();
      const rects = all.filter(
        (a) => a.metadata?.toolName === "RectangleROI"
      );
      rects.forEach((a) => mgr.removeAnnotation(a.annotationUID));
      renderingEngine?.getViewports().forEach((vp) => vp.render());
      countAnnotations();
    } catch (e) {
      console.error("Error clearing annotations:", e);
    }
  };

  const handleSubmit = () => {
    try {
      const mgr = cornerstoneTools.annotation.state;
      const all = mgr.getAllAnnotations();
      const rects = all.filter(
        (a) => a.metadata?.toolName === "RectangleROI" && !a.isLocked
      );

      if (rects.length === 0) {
        toast.info("Draw at least one bounding box before submitting", {
          duration: 2000,
        });
        return;
      }

      const boxes = rects.map((a) => ({
        imageId: a.metadata?.referencedImageId || "",
        points: a.data?.handles?.points || [],
      }));

      const payload = {
        userId: userData.id,
        userName:
          userData.user_metadata?.full_name || userData.email || "Anonymous",
        boxes,
      };

      if (interactionChannel) {
        interactionChannel.send({
          type: "broadcast",
          event: "annotations-submitted",
          payload,
        });
      }

      dispatch({ type: "annotation_received", payload });

      rects.forEach((a) => {
        a.isLocked = true;
        a.autoGenerated = true;
      });
      renderingEngine?.getViewports().forEach((vp) => vp.render());
      countAnnotations();

      toast.success(`Submitted ${boxes.length} annotation(s)`, {
        duration: 2000,
      });
    } catch (e) {
      console.error("Error submitting annotations:", e);
    }
  };

  const handleClearSubmissions = () => {
    dispatch({ type: "clear_all_annotations" });
    if (renderingEngine) {
      renderingEngine.getViewports().forEach((vp) => clearBoxHeatmap(vp));
    }
  };

  const showAnnotateControls = toolSelected === "annotate" && !isSessionOwner;
  const showHeatmapControls = isSessionOwner && submissionCount > 0 && heatmapVisible;

  if (!showAnnotateControls && !showHeatmapControls) return null;

  if (showHeatmapControls && !showAnnotateControls) {
    return (
      <div className="fixed bottom-4 left-1/2 -translate-x-1/2 z-40 flex items-center gap-2 px-3 py-1.5 rounded-2xl bg-slate-900/90 border border-slate-700 shadow-lg backdrop-blur-sm">
        <span className="text-[10px] px-2 py-0.5 text-slate-400 whitespace-nowrap">
          {submissionCount} user{submissionCount !== 1 ? "s" : ""} &middot;{" "}
          {totalBoxes} box{totalBoxes !== 1 ? "es" : ""}
        </span>

        <div className="w-px h-4 bg-slate-700" />

        <button
          onClick={() => dispatch({ type: "toggle_heatmap" })}
          className="text-[10px] px-2 py-0.5 rounded-full border transition-colors flex items-center gap-1.5 bg-blue-600/20 border-blue-500/50 text-blue-400"
          title={heatmapVisible ? "Hide heatmap" : "Show heatmap"}
        >
          {heatmapVisible ? (
            <EyeOff className="h-3 w-3" />
          ) : (
            <Eye className="h-3 w-3" />
          )}
          {heatmapVisible ? "Hide" : "Show"}
        </button>

        <button
          onClick={handleClearSubmissions}
          className="text-[10px] text-slate-400 hover:text-red-400 transition-colors font-medium"
          title="Clear all submissions"
        >
          Clear
        </button>
      </div>
    );
  }

  return (
    <div className="fixed bottom-4 left-1/2 -translate-x-1/2 z-40 flex items-center gap-2 px-3 py-1.5 rounded-2xl bg-slate-900/90 border border-slate-700 shadow-lg backdrop-blur-sm">
      <span className="text-[10px] text-slate-400 whitespace-nowrap">
        {annotationCount} box{annotationCount !== 1 ? "es" : ""}
      </span>

      <div className="w-px h-4 bg-slate-700" />

      <button
        onClick={handleClearAll}
        disabled={totalAnnotationCount === 0}
        className={`text-[10px] px-2 py-0.5 rounded-full border transition-colors flex items-center gap-1.5 ${
          totalAnnotationCount > 0
            ? "bg-slate-800 border-slate-600 text-slate-200"
            : "bg-slate-900 border-slate-800 text-slate-500 cursor-not-allowed"
        }`}
      >
        <Trash2 className="h-3 w-3" />
        Clear
      </button>

      <button
        onClick={handleSubmit}
        disabled={annotationCount === 0}
        className={`text-[10px] px-2 py-0.5 rounded-full border transition-colors flex items-center gap-1.5 ${
          annotationCount > 0
            ? "bg-blue-600/20 border-blue-500/50 text-blue-400"
            : "bg-slate-900 border-slate-800 text-slate-500 cursor-not-allowed"
        }`}
      >
        <Send className="h-3 w-3" />
        Submit
      </button>

      <div className="w-px h-4 bg-slate-700" />

      <span className="text-[10px] text-slate-500 whitespace-nowrap">
        Click box + Del to remove
      </span>
    </div>
  );
}

export default AnnotationPanel;
export { AnnotationPanel };
