import { FrameOfReferenceSpecificAnnotationManager } from '@cornerstonejs/tools/src/stateManagement/annotation'

import {
  Enums,
  eventTarget,
  getEnabledElement,
  Types,
  utilities,
} from '@cornerstonejs/core';


class AnnotationManager extends FrameOfReferenceSpecificAnnotationManager {
  /**
   * @param uid - The uid of the state manager. If omitted it is autogenerated.
   */
  constructor(uid?: string) {
    super(uid);
  }
}

const defaultAnnotationManager =
  new AnnotationManager('AtTheViewBox');

export { defaultAnnotationManager };
